name: Metrics
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options Plugins
          user: JuanPabloDiaz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          # Isometric Contributions
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # Stargazers
          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 14
          # GitHub Projects
          plugin_projects: yes
          plugin_projects_limit: 4
          # Languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: Jupyter%20Notebook, scss, ruby, shell, python
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          # Lines of Code
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          # Starred topics
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          # Recently Starred Repositories
          plugin_stars: no # disabled
          plugin_stars_limit: 4
          # Coding Habits & Activity
          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%
          # Issues & PRs
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories
          # Comments reactions
          plugin_reactions: no # disabled
          plugin_reactions_display: absolute
          plugin_reactions_limit: 200
          plugin_reactions_limit_discussions: 100
          plugin_reactions_limit_discussions_comments: 100
          plugin_reactions_limit_issues: 100
          # People
          plugin_people: no # disabled
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          # Featured Repositories
          plugin_repositories: yes
          plugin_repositories_order: featured, pinned, starred, random
          # Commit Calendar
          plugin_calendar: yes
          plugin_calendar_limit: 1
          # Achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          # Notable contributions
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_types: commit
